config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :settings
  resources :posts

  root to: "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content
  has_attached_file :image
  validates :image, attachment_presence: true
  validates_attachment_content_type :image, content_type: /\Aimage/
  do_not_validate_attachment_file_type :image
end

app/models/setting.rb
class Setting < ApplicationRecord
  has_attached_file :image
  validates :image, attachment_presence: true
  validates_attachment_content_type :image, content_type: /\Aimage/
  do_not_validate_attachment_file_type :image
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :title, :image)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to root_url, notice: 'Setting was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to root_url, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin
    user_logged
  end

  def user_logged
    current_user&.is_admin
  end

  def setting_url_for_layout
    setting = Setting.first
    setting ? edit_setting_url(setting) : new_setting_url
  end

  def main_setting
    Setting.first
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DamianPosts</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <% if main_setting %>
          <%= image_tag main_setting.image.url, class: 'img-thumbnail', size: "150x30" %>
        <% else %>
          Aby ustawić logo wejdź w ustawienia
        <% end %>
        <%= link_to "Damian Olejnik", root_url, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Home", root_url, class: "nav-link" %>
            </li>
            <% if is_admin %>
              <li class="nav-item active">
                <%= link_to "Dodaj wpis", new_post_url, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          <div class="pull-right">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-cog"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Ustawienia", setting_url_for_layout, class: 'dropdown-item' %>
                  <%= link_to("Zaloguj", new_user_session_url, class: 'dropdown-item') unless user_signed_in? %>
                  <%= link_to("Wyloguj", destroy_user_session_path, method: :delete, class: 'dropdown-item') if user_signed_in? %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, "Zapisz" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>

  <% if @posts.any? %>
    <h1>Wszystkie posty<h1>
  <% else %>
    <h2>Brak postów do wyświetlenia</h2>
  <% end %>

  <% @posts.each do |post| %>
    <h3>
      <%= image_tag post.image.url, class: "img-thumbnail", width: 100 %>
      <%= post.title %>
    </h3>
    <div>
      <%= truncate(raw post.content) %>
      <%= link_to "czytaj dalej", post %>
    </div>
    <% if is_admin %>
      <%= link_to "Edytuj", edit_post_url(post) %>
      <%= link_to "Usuń", post, method: :delete, data: { confirm: "Usunąć wpis?" } %>
    <% end %>
    <hr />
  <% end %>
<% else %>
  Zaloguj się aby przeglądać posty
<% end %>

app/views/posts/new.html.erb
<h1>Nowy post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h3>
  <%= @post.title %>
</h3>
<div>
  <%= image_tag @post.image.url %>
</div>
<p>
  <%= raw @post.content %>
</p>

app/views/settings/_form.html.erb
<%= simple_form_for @setting, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, "Zapisz" %>
<% end %>

app/views/settings/edit.html.erb
<%= render 'form', setting: @setting %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.image %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<%= render 'form', setting: @setting %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @setting.image %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>